services:
  mongodp:
    image: mongo:7.0-jammy

    container_name: mongodp

    ports:
      - "27007:27017"

    volumes:
      - mongodata:/data/dp

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
      
    restart: always



networks:
  backend:

volumes:
  mongodata:
  




# sudo docker stop $(sudo docker ps -aq) -> stop all containers
# sudo docker rm $(sudo docker ps -aq)-> delete all containers 
# sudo docker rmi $(sudo docker images -q)-> delete all images 
# sudo docker volume rm $(sudo docker volume ls -q)-> delete all volumes 
# sudo docker system prune --all  -> delete every thing not used
# sudo docker compose up -d











